import type React from 'react';

const S: Record<string, React.CSSProperties> = {
  root:{background:"var(--bg)",backgroundImage:"radial-gradient(ellipse at 50% 0%, var(--accent-glow) 0%, transparent 60%)",minHeight:"100vh",fontFamily:"'DM Sans',sans-serif",color:"var(--text)",WebkitTextSizeAdjust:"100%",position:"relative"},
  loadWrap:{background:"var(--bg)",minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"},
  loadText:{fontSize:16,color:"var(--muted)",fontWeight:400,fontFamily:"'Space Grotesk',sans-serif",letterSpacing:"0.3px"},
  header:{background:"var(--header-bg)",borderBottom:"1px solid var(--border)",position:"sticky",top:0,zIndex:50,transition:"box-shadow .3s",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)"},
  headerInner:{margin:"0 auto",padding:"14px 28px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12},
  logo:{fontSize:24,fontWeight:700,letterSpacing:"-0.5px",color:"var(--text)",fontFamily:"'Space Grotesk',sans-serif"},
  logoSub:{fontSize:13,color:"var(--accent)",fontWeight:500,fontFamily:"'Space Grotesk',sans-serif",letterSpacing:"0.5px",opacity:.8},
  tabs:{display:"flex",gap:3,background:"var(--chip)",borderRadius:14,padding:3,backdropFilter:"blur(8px)",WebkitBackdropFilter:"blur(8px)"},
  tab:{padding:"9px 20px",borderRadius:11,border:"none",cursor:"pointer",background:"transparent",color:"var(--muted)",fontWeight:500,fontSize:14,fontFamily:"'DM Sans',sans-serif",transition:"all .25s",minHeight:40},
  tabActive:{background:"var(--accent)",color:"#fff",boxShadow:"0 2px 12px var(--accent-glow)"},
  main:{margin:"0 auto",padding:"28px 28px 60px"},
  catSidebar:{background:"var(--card)",borderRadius:16,border:"1px solid var(--border)",padding:14,width:240,flexShrink:0,position:"sticky",top:80,transition:"border-color .25s",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  catSidebarHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10,paddingBottom:8,borderBottom:"1px solid var(--border)"},
  catSidebarList:{display:"flex",flexDirection:"column",gap:2},
  catSideItem:{display:"flex",alignItems:"center",gap:6,padding:"10px 12px",borderRadius:10,border:"none",cursor:"pointer",background:"transparent",color:"var(--muted)",fontWeight:500,fontSize:14,fontFamily:"'DM Sans',sans-serif",width:"100%",transition:"all .2s",textAlign:"left",minHeight:42},
  catSideItemActive:{background:"var(--accent)",color:"#fff",boxShadow:"0 4px 16px var(--accent-glow)"},
  loanBadgeSide:{fontSize:8,padding:"2px 6px",borderRadius:4,background:"var(--accent-light)",color:"var(--accent)",fontWeight:600,whiteSpace:"nowrap"},
  yearNav:{display:"flex",alignItems:"center",gap:12,marginBottom:18},
  yearBtn:{background:"none",border:"none",cursor:"pointer",fontSize:22,color:"var(--muted)",padding:10,borderRadius:10,minWidth:44,minHeight:44,display:"flex",alignItems:"center",justifyContent:"center",transition:"all .25s"},
  yearLabel:{fontSize:24,fontWeight:700,minWidth:60,textAlign:"center",color:"var(--text)",fontFamily:"'Space Grotesk',sans-serif",letterSpacing:"-0.3px"},
  yearRange:{fontSize:11,color:"var(--faintest)",marginLeft:8},
  listWrap:{background:"var(--card)",borderRadius:16,border:"1px solid var(--border)",overflowX:"auto",marginBottom:16,WebkitOverflowScrolling:"touch",transition:"border-color .25s",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  listHeader:{display:"flex",alignItems:"center",gap:12,padding:"10px 18px",fontSize:11,fontWeight:600,color:"var(--muted)",textTransform:"uppercase",letterSpacing:1,borderBottom:"1px solid var(--border)",background:"var(--card-alt)",minHeight:42,backdropFilter:"blur(8px)",WebkitBackdropFilter:"blur(8px)"},
  listRow:{display:"flex",alignItems:"center",gap:12,padding:"14px 18px",borderBottom:"1px solid var(--border-light)",cursor:"pointer",transition:"background .2s, opacity .15s",minHeight:52},
  listRowCurrent:{background:"var(--accent-bg)"},
  nowBadge:{fontSize:9,padding:"2px 8px",borderRadius:5,background:"var(--accent)",color:"#fff",fontWeight:600,animation:"popIn .3s",boxShadow:"0 0 10px var(--accent-glow)"},
  yearTotal:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"var(--card)",borderRadius:14,border:"1px solid var(--border)",backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)"},
  sectionHead:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:18,flexWrap:"wrap",gap:12},
  sectionTitle:{fontSize:24,fontWeight:700,color:"var(--text)",fontFamily:"'Space Grotesk',sans-serif",letterSpacing:"-0.3px"},
  sectionSub:{color:"var(--muted)",fontSize:13,marginTop:4},
  incomeCard:{background:"var(--card)",borderRadius:16,padding:20,border:"1px solid var(--border)",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  timeChip:{fontSize:12,padding:"6px 12px",borderRadius:8,background:"var(--chip)",color:"var(--text2)",transition:"all .2s",border:"1px solid var(--border-light)"},
  tableWrap:{background:"var(--card)",borderRadius:16,border:"1px solid var(--border)",overflow:"hidden",WebkitOverflowScrolling:"touch",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  tableHeader:{display:"flex",padding:"10px 16px",fontSize:11,fontWeight:600,color:"var(--muted)",textTransform:"uppercase",letterSpacing:1,borderBottom:"1px solid var(--border)",minHeight:42},
  tableRow:{display:"flex",alignItems:"center",padding:"12px 16px",borderBottom:"1px solid var(--border-light)",transition:"background .2s",minHeight:48},
  btnPrimary:{background:"var(--accent)",color:"#fff",border:"none",padding:"12px 22px",borderRadius:12,fontSize:15,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",transition:"all .25s",minHeight:44,boxShadow:"0 2px 8px var(--accent-glow)"},
  btnGhost:{background:"transparent",color:"var(--muted)",border:"1px solid var(--border-input)",padding:"9px 16px",borderRadius:10,fontSize:13,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",minHeight:40,transition:"all .25s"},
  btnGhostModal:{background:"transparent",color:"var(--muted)",border:"1px solid var(--border-input)",padding:"12px 18px",borderRadius:12,fontSize:15,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",minHeight:44,transition:"all .25s"},
  btnSmall:{background:"none",border:"1px solid var(--border-input)",padding:"6px 12px",borderRadius:8,fontSize:13,cursor:"pointer",color:"var(--text2)",fontFamily:"'DM Sans',sans-serif",minHeight:34,transition:"all .2s"},
  deleteLink:{display:"block",width:"100%",textAlign:"center",marginTop:12,padding:12,background:"none",border:"none",color:"var(--red)",fontSize:14,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",opacity:.65,minHeight:44,transition:"opacity .25s"},
  overlay:{position:"fixed",inset:0,background:"var(--overlay)",backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:999,padding:20,animation:"fadeIn .2s"},
  modalContent:{background:"var(--modal-bg)",borderRadius:24,padding:30,width:"100%",maxWidth:620,maxHeight:"90vh",overflowY:"auto",boxShadow:"0 24px 80px var(--shadow-lg), 0 0 1px rgba(255,255,255,0.05) inset",WebkitOverflowScrolling:"touch",backdropFilter:"blur(24px)",WebkitBackdropFilter:"blur(24px)",border:"1px solid var(--border)"},
  modalTitle:{fontSize:24,fontWeight:700,marginBottom:4,color:"var(--text)",fontFamily:"'Space Grotesk',sans-serif",letterSpacing:"-0.3px"},
  label:{fontSize:11,fontWeight:600,color:"var(--muted)",display:"block",marginBottom:5,textTransform:"uppercase",letterSpacing:1,fontFamily:"'Space Grotesk',sans-serif"},
  checkLabel:{display:"flex",alignItems:"center",fontSize:14,color:"var(--text2)",padding:"12px 14px",background:"var(--chip2)",borderRadius:12,cursor:"pointer",marginTop:4,minHeight:44,transition:"background .2s",border:"1px solid var(--border-light)"},
  summaryCard:{background:"var(--card)",borderRadius:18,padding:"22px 24px",border:"1px solid var(--border)",transition:"transform .3s cubic-bezier(.22,1,.36,1), box-shadow .3s, border-color .3s",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  chartCard:{background:"var(--card)",borderRadius:18,padding:24,border:"1px solid var(--border)",marginBottom:14,backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  chartTitle:{fontSize:15,fontWeight:600,margin:"0 0 14px",color:"var(--text)",fontFamily:"'Space Grotesk',sans-serif"},
  th:{padding:"10px 12px",textAlign:"left",fontSize:11,fontWeight:600,color:"var(--muted)",textTransform:"uppercase",letterSpacing:.5,fontFamily:"'Space Grotesk',sans-serif"},
  td:{padding:"10px 12px",textAlign:"left",color:"var(--text)"},
  toast:{position:"fixed",bottom:28,left:"50%",transform:"translateX(-50%)",zIndex:1000,background:"var(--toast-bg)",color:"var(--toast-fg)",padding:"12px 28px",borderRadius:14,fontSize:14,fontWeight:500,animation:"toastIn .3s",boxShadow:"0 8px 32px var(--shadow-lg)",maxWidth:"calc(100vw - 40px)",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)",border:"1px solid var(--border)"},
  emptyState:{textAlign:"center",padding:"52px 28px",color:"var(--muted)",fontSize:14,background:"var(--card)",borderRadius:18,border:"1px dashed var(--border-input)",animation:"fadeIn .4s",backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)"},
};
export default S;
